# vulnerability_index_config.yaml
name: vulnerability-index
fields:
  # Primary Key
  - name: id
    type: Edm.String
    key: true
    sortable: true
    searchable: true
    retrievable: true

  # Record Identifier
  - name: number
    type: Edm.Int32
    filterable: true
    sortable: true
    facetable: true
    retrievable: true

  # Assignment and Service Information
  - name: assignment_group
    type: Edm.String
    searchable: true
    filterable: true
    sortable: true
    retrievable: true

  - name: assignment_group_vendor
    type: Edm.String
    searchable: true
    filterable: true
    retrievable: true

  - name: cms_associated_service_name
    type: Edm.String
    searchable: true
    filterable: true
    retrievable: true

  - name: cms_reporting_sector
    type: Edm.String
    searchable: true
    filterable: true
    retrievable: true

  - name: cms_sector
    type: Edm.String
    searchable: true
    filterable: true
    retrievable: true

  - name: cms_service_area
    type: Edm.String
    searchable: true
    filterable: true
    retrievable: true

  # Infrastructure Information
  - name: ip_address
    type: Edm.String
    searchable: true
    filterable: true
    retrievable: true

  - name: cmdb_ci
    type: Edm.String
    searchable: true
    filterable: true
    retrievable: true

  - name: ci_class
    type: Edm.String
    searchable: true
    filterable: true
    retrievable: true

  - name: os
    type: Edm.String
    searchable: true
    filterable: true
    retrievable: true

  - name: is_dmz
    type: Edm.Boolean
    filterable: true
    retrievable: true

  # Vulnerability Details
  - name: vulnerability
    type: Edm.String
    searchable: true
    filterable: true
    retrievable: true

  - name: app_and_tech
    type: Edm.String
    searchable: true
    filterable: true
    retrievable: true

  - name: category
    type: Edm.String
    searchable: true
    filterable: true
    retrievable: true

  - name: software_group
    type: Edm.String
    searchable: true
    filterable: true
    retrievable: true

  # Detailed Information
  - name: summary
    type: Edm.String
    searchable: true
    retrievable: true
    analyzer: "standard.lucene"  # Good for longer text content

  - name: remediation_note
    type: Edm.String
    searchable: true
    retrievable: true
    analyzer: "standard.lucene"

  - name: proof
    type: Edm.String
    searchable: true
    retrievable: true

  # Temporal Data
  - name: last_opened
    type: Edm.DateTimeOffset
    filterable: true
    sortable: true
    retrievable: true

  - name: age_days
    type: Edm.Int32
    filterable: true
    sortable: true
    facetable: true
    retrievable: true

  - name: age
    type: Edm.Int32
    filterable: true
    sortable: true
    facetable: true
    retrievable: true

  # RPM Metrics
  - name: load_time_debt
    type: Edm.Double
    filterable: true
    sortable: true
    facetable: true
    retrievable: true

  - name: eom_debt
    type: Edm.Double
    filterable: true
    sortable: true
    facetable: true
    retrievable: true

  - name: ola_priority
    type: Edm.String
    searchable: true
    filterable: true
    sortable: true
    retrievable: true

  # Security Flags
  - name: is_critical_server
    type: Edm.Boolean
    filterable: true
    retrievable: true

  - name: has_exploit
    type: Edm.Boolean
    filterable: true
    retrievable: true

  - name: port
    type: Edm.Int32
    filterable: true
    sortable: true
    retrievable: true

  # System Timestamps
  - name: last_found
    type: Edm.DateTimeOffset
    filterable: true
    sortable: true
    retrievable: true

  - name: created_on
    type: Edm.DateTimeOffset
    filterable: true
    sortable: true
    retrievable: true

  - name: updated_on
    type: Edm.DateTimeOffset
    filterable: true
    sortable: true
    retrievable: true

  - name: load_datetime
    type: Edm.DateTimeOffset
    filterable: true
    sortable: true
    retrievable: true

  # Vector Embedding
  - name: embedding
    type: Collection(Edm.Single)
    searchable: true
    dimensions: 1536
    vector_search_profile: vector-profile-vulnerability-index

vector_search:
  algorithm_name: vector-config
  metric: cosine
  m: 4
  ef_construction: 400
  ef_search: 500
  profile_name: vector-profile-vulnerability-index
  vectorizer_name: vulnerability-vectorizer
  vectorizer_deployment_id: text-embedding-ada-002
  vectorizer_model_name: text-embedding-ada-002

# Fields to use for generating embeddings
embedding_fields:
  - summary
  - vulnerability
  - remediation_note
  - app_and_tech
  - os
  - is_critical_server
  - has_exploit
  - category
  - software_group

# Search Suggestions
suggesters:
  - name: vuln-suggester
    source_fields:
      - vulnerability
      - app_and_tech
      - software_group

# Scoring Profile
scoring_profiles:
  - name: vulnerabilityScorer
    text_weights:
      weights:
        vulnerability: 5
        summary: 4
        remediation_note: 3
    functions:
      - type: freshness
        field_name: last_found
        boost: 2
      - type: magnitude
        field_name: age_days
        boost: 1.5
        interpolation: linear
      - type: tag
        field_name: is_critical_server
        tag_boost: 
          "true": 2.0